name: Orchestrate Workflows
on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: 'Environment to deploy (e.g., dev, staging, prod)'
      tag:
        required: true
        description: 'Docker tag to use'

jobs:
  trigger-application-workflow:
    uses: owner/repo-app-code/.github/workflows/application-workflow.yml@main
    with:
      environment: ${{ inputs.environment }}

  trigger-docker-workflow:
    uses: owner/repo-docker-files/.github/workflows/docker-workflow.yml@main
    with:
      tag: ${{ inputs.tag }}
